name: 'Minify-JSON'
author: 'Stefan Ensmann'
description: 'Minify JSON files'
branding:
  color: 'yellow'
  icon: 'minimize-2'
runs:
  using: 'composite'
  steps:
    - run: find . -name "*.json" -print | xargs python ${{ github.action_path }}/minify.py
      shell: bash
